# Generated by Django 5.2.1 on 2025-05-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_establishment_creation_year_alter_establishment_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='tenant_id',
            field=models.UUIDField(default=None, editable=False, unique=True),
        ),
    ]
