from .user import UserSerializer
from .establishment import EstablishmentSerializer
from .level import LevelSerializer
from .department import DepartmentSerializer
from .subject import SubjectSerializer
from .professor import ProfessorSerializer
from .student import StudentSerializer
from .exam import ExamSerializer
from .attendance import AttendanceSerializer