from .user import User
from .establishment import Establishment
from .level import Level
from .department import Department
from .subject import Subject
from .professor import Professor
from .student import Student
from .exam import Exam
from .attendance import Attendance